app:
  config:
    keycloak:
      url: http://localhost:8081
      realm: workoutnow

spring:
  application:
    name: msgeneral
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/workoutnowgeneral
    platform: postgres
    password: mysecretpassword
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  database:
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}

server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

